############################
#       REVERSE PROXY      #
############################

version: '3'
services:
 reverse_proxy:
  image: nginx:1.23.3-alpine
  volumes:
   - ./includes:/etc/nginx/includes
   - ./conf.d:/etc/nginx/conf.d
   - ./data/certbot/conf:/etc/letsencrypt:ro
   - ./data/certbot/www:/var/www/certbot:ro
   - ../authelia/config/nginx:/etc/nginx/includes
   - ../authelia/config/nginx/:/etc/nginx/config.d
  ports:
   - "80:80"
   - "443:443"
  networks:
   - authelia-net
  restart:
    always

 certbot:
  image: certbot/certbot:latest
  volumes:
   - ./data/certbot/conf:/etc/letsencrypt:rw
   - ./data/certbot/www:/var/www/certbot:rw

networks:
  authelia-net:
    external: true
